name: Lifecycle basic initialization e2e tests ♻️

on:
  pull_request:
    branches: [main]

jobs:
  lc-init-tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'test-lifecycle')
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [18.x]

    env:
      PR_NUMBER: ${{ github.event.number }}
      PR_BRANCH: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile
        env:
          NPM_TOKEN_GH_GOODRX_CI: ${{secrets.NPM_TOKEN}}

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Lifecycle initial tests
        run: |
          echo "Running initial lifecycle tests!" &&
          pnpm exec playwright test tests/lc-init.spec.ts
